# This file is part of icmr
#
# Copyright (C) 2020, David Senhora Navega
#
# icmr is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# icmr is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with icmr. If not, see <http://www.gnu.org/licenses/>.
#
# David Senhora Navega
# Laboratory of Forensic Anthropology
# Department of Life Sciences
# University of Coimbra
# Calçada Martim de Freitas, 3000-456, Coimbra
# Portugal

#' Inductive Confidence Machine for Regression Control
#'
#' @author David Navega
#' @export
#'
#' @param alpha a numeric defining the tolerance or confidence (1 - alpha) of
#' the predictive intervals of icmr model. Default is 0.05
#' @param process a logical stating if the data should be internally processed
#' by standardization.
#' @param interval a vector of the numeric values defining the domain of the
#' predictions generated by the icmr model. Default is NULL which means that
#' the interval is computed from the data.
#'
#' @return a list with the parameters given as arguments to the function call.
#'
icmr.control <- function(alpha = 0.05, process = T, interval = NULL) {

  if (alpha < 0.01  | alpha > 0.5)
    stop("\n(-) alpha must be a numeric value between 0.01 and 0.5.")

  control.list <- structure(
    .Data = list(
      alpha = alpha,
      process = process,
      interval = interval,
      truncate = T
    ),
    class = "icmr.control"
  )

  return(control.list)

}

#' @author David Senhora Navega
#' @noRd
#'
is.icmr.control <- function(x) inherits(x = x, what = "icmr.control")
